export const wardrobe = {
  tops: [
    "white t-shirt",
    "black turtleneck",
    "striped long-sleeve",
    "silk camisole",
    "graphic hoodie",
    "denim shirt",
    "floral blouse",
    "linen button-down",
  ],
  bottoms: [
    "blue jeans",
    "black trousers",
    "khaki chinos",
    "denim shorts",
    "pleated midi skirt",
    "leather leggings",
    "corduroy pants",
    "flowy maxi skirt",
  ],
  layers: [
    "denim jacket",
    "leather jacket",
    "beige trench coat",
    "grey cardigan",
    "oversized blazer",
    "puffer vest",
    "wool peacoat",
  ],
  accessories: [
    "gold necklace",
    "silver hoops",
    "leather belt",
    "sunglasses",
    "beanie",
    "silk scarf",
    "tote bag",
    "crossbody purse",
  ],
  footwear: [
    "white sneakers",
    "black ankle boots",
    "brown loafers",
    "strappy sandals",
    "platform heels",
    "combat boots",
    "espadrilles",
  ],
};
